'use client';

import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import {usePathname} from 'next/navigation';
import NewsField from '@/components/Home/newsfield/NewsField';
import './globals.css';
import {useEffect} from "react";

const metadata = {
    title: 'kohan',
    description: 'Generated by create next app',
};

export default function RootLayout({children}) {
    const router = usePathname();

    useEffect(() => {
        window.scrollTo(0, 0)
    }, [router])

    const r = router.substring(1)
        .split('-')
        .reduce((t, c) => t + " " + c)
    const rr = router.split('/')
    let text = ''
    if (router === '/'){
        text = 'It has an exhibition grade from the Ministry of Industry, Mines and Trade'
    } else if (rr.length === 1){
        text = r.toUpperCase()
    } else if(rr.length > 1){
        text = rr[1].toUpperCase()
    }

    return (
        <html lang="en" dir="rtl">
        <body>
        <main>
            <Header
                title={text}
            />
            <div id="a"></div>
            {children}
            <NewsField/>
            <Footer/>
        </main>
        </body>
        </html>
    );
}
