'use client';

import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import {usePathname} from 'next/navigation';
import NewsField from '@/components/Home/newsfield/NewsField';
import './globals.css';
import {useEffect} from "react";

const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({children}) {
    const router = usePathname();

    useEffect(() => {
        window.scrollTo(0, 0)
    }, [router])

    const r = router.substring(1)
        .split('-')
        .reduce((t, c) => t + " " + c)
        .split('/')
        .reduce((t, c) => t + " " + c)


    return (
        <html lang="en" dir="rtl">
        <body>
        <main>
            <Header
                title={`${
                    router === '/'
                        ? 'It has an exhibition grade from the Ministry of Industry, Mines and Trade'
                        : r.toUpperCase()
                }`}
            />
            <div id="a"></div>
            {children}
            <NewsField/>
            <Footer/>
        </main>
        </body>
        </html>
    );
}
